# Generated by Django 4.1.1 on 2022-11-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeforquestion',
            name='target',
        ),
        migrations.RemoveField(
            model_name='likeforquestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='LikeForQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
