# Generated by Django 4.1.1 on 2022-11-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='supplement',
            field=models.TextField(blank=True, verbose_name='補足'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#c8c8c8', max_length=7, verbose_name='色'),
        ),
    ]
