# Generated by Django 4.1.1 on 2022-10-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image3',
        ),
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='answer_img/', verbose_name='画像'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='question_img/', verbose_name='画像'),
        ),
    ]
