# Generated by Django 4.1.1 on 2022-11-14 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_question_supplement_alter_subject_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytime',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study.subject', verbose_name='教科'),
        ),
    ]
