# Generated by Django 4.1.1 on 2022-11-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_studytime_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_learned',
            field=models.BooleanField(default=False, verbose_name='学習済み'),
        ),
    ]
