# Generated by Django 4.1.1 on 2022-11-14 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_subject_is_learned'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='使用可能'),
        ),
        migrations.AlterField(
            model_name='studytime',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study.subject', verbose_name='教科'),
        ),
    ]
