# Generated by Django 4.1.1 on 2022-11-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_subject_is_available_alter_studytime_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_available',
        ),
        migrations.AddField(
            model_name='subject',
            name='is_disable',
            field=models.BooleanField(default=False, verbose_name='使用不可'),
        ),
    ]
