# Generated by Django 4.1.1 on 2022-11-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, verbose_name='お礼コメント'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_self_resolution',
            field=models.TextField(blank=True, verbose_name='自己解決'),
        ),
    ]
