# Generated by Django 4.1.1 on 2022-11-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='回答文'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='質問文'),
        ),
    ]
